SELECT AVG(SALARIO) FROM EMPREGADO;

SELECT COUNT(ESSN) FROM TRABALHA_EM T
    JOIN EMPREGADO E on T.ESSN = E.SSN
    WHERE DNO = 5 AND PNO = 1 AND HORAS > 10;

SELECT COUNT(ESSN) FROM EMPREGADO E
    LEFT JOIN DEPENDENTE D on E.SSN = D.ESSN
    WHERE PNOME LIKE  CONCAT('%', NOME_DEPENDENTE, '%');

SELECT E.PNOME EMPREGADO FROM  EMPREGADO AS E
    JOIN EMPREGADO AS S ON E.SUPERSSN = S.SSN
    WHERE S.PNOME LIKE 'Franklin';

SELECT SUM(SALARIO) FROM EMPREGADO E
    JOIN DEPARTAMENTO D ON E.DNO = D.DNUMERO
    WHERE DNOME LIKE '%Research%';

SELECT SUM(SALARIO+SALARIO*0.1) FROM EMPREGADO E
    JOIN TRABALHA_EM T ON E.SSN = T.ESSN
    JOIN PROJETO P ON T.PNO = P.PNUMERO
    WHERE PJNOME LIKE '%ProductX%';

SELECT DNOME, AVG(SALARIO) FROM DEPARTAMENTO D
    JOIN EMPREGADO E ON D.DNUMERO = E.DNO
    GROUP BY DNOME
    ORDER BY AVG(SALARIO);
